# ใช้ Node.js image
FROM node:20

# ตั้งค่า working directory
WORKDIR /usr/src/app

# คัดลอกโค้ดแอปพลิเคชันไปยัง working directory
COPY . .

# ติดตั้ง dependencies
RUN npm install

# สร้างแอปพลิเคชัน
RUN npm run build
RUN rm -rf ./src

# ตั้งค่า port ที่จะใช้งาน
EXPOSE 8000

# รันแอปพลิเคชัน
CMD ["npm", "run", "start:prod"]
