version: '3.4'

services:
  nestjsmysqldocker:
    image: nestjsmysqldocker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
