version: '3.4' # กำหนด docker version
services:
  nestjs-api:
    image: nestjs-api # กำหนดชื่อ image
    container_name: node
    build: # ตำแหน่ง Dockerfile
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000' # map port ออกมา เหมือน -p ใน docker run
    environment:
      - PORT=8000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src

  mysql-server:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nestjs_db
    ports:
      - '3306:3306'
    volumes:
      - c:/mysql-data:/var/lib/mysql

  phpmyadmin-server:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-server
    ports:
      - '8080:80'
    depends_on:
      - mysql-server
